apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Microservicio de pagos
  annotations:
    github.com/project-slug: TU_USUARIO_DE_GITHUB/payment
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: financial-system